version: '3.1'

networks:
  backbone:
    external:
      true

services:

  service-template:
    container_name: service-template
    build: .
    networks:
    - backbone
    ports:
    - 8070:8070
